routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\SucursalController;
use App\Http\Controllers\SalaController;
use App\Http\Controllers\ProyeccionController;
use App\Http\Controllers\PeliculaController;
use App\Http\Controllers\AsientoController;
use App\Http\Controllers\ReservaController;
use App\Http\Controllers\ViewUserController;
use Illuminate\Contracts\View\View;

Route::get('/', function () {
    return view('dashboard');
});
Route::get('/dashboard', function () {return view('dashboard');})->name('dashboard');
Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified',])->group(function () {
    

    Route::group(['middleware' => ['auth', 'admin']], function () {
        Route::resource('horarios', 'HorarioController');

        Route::get('admin', [AdminController::class, 'index'])->name('admin.index');

        // Rutas para Sucursales
        Route::delete('/sucursal/{id}', [SucursalController::class, 'destroy'])->name('sucursales.destroy');
        
        Route::get('/sucursal/create', [SucursalController::class, 'create'])->name('sucursales.create');
        Route::post('/sucursal', [SucursalController::class, 'store'])->name('sucursales.store');
        

        // Rutas para Salas
        Route::post('/salas', [SalaController::class, 'store'])->name('salas.store');
        Route::get('/salas/create', [SalaController::class, 'create'])->name('salas.create');
        
        Route::delete('/salas/{id}', [SalaController::class, 'destroy'])->name('salas.destroy');
        // Route::get('/salas/{id}/edit', [SalaController::class, 'store'])->name('salas.store');

        
        
    });

    Route::group(['middleware' => ['auth', 'mod']], function () {

        Route::get('admin', [AdminController::class, 'index'])->name('admin.index');

        // Rutas para Sucursales MOD
        Route::get('/sucursal', [SucursalController::class, 'index'])->name('sucursales.index');
        Route::get('/sucursal/{sucursal}', [SucursalController::class, 'show'])->name('sucursal.show');

        // Rutas para Salas MOD
        Route::get('/salas/{slug}', [SalaController::class, 'show'])->name('salas.show');

        // Rutas para Proyecciones
        Route::get('/proyecciones/create/{sala_id}', [ProyeccionController::class, 'create'])->name('proyecciones.create');
        Route::post('/proyeccion', [ProyeccionController::class, 'store'])->name('proyecciones.store');
        Route::get('/proyeccion/{id}', [ProyeccionController::class, 'show'])->name('proyecciones.show');
        Route::delete('/proyecciones/{id}', [ProyeccionController::class, 'destroy'])->name('proyecciones.destroy');

        // Ruta para listar Películas
        Route::delete('/pelicula/{id}', [PeliculaController::class, 'destroy'])->name('peliculas.destroy');
        Route::get('/pelicula', [PeliculaController::class, 'index'])->name('peliculas.index');
        Route::get('/pelicula/create', [PeliculaController::class, 'create'])->name('peliculas.create');
        Route::get('/pelicula/{id}', [PeliculaController::class, 'show'])->name('peliculas.show');
        Route::get('pelicula/{id}/edit', [PeliculaController::class, 'edit'])->name('peliculas.edit');
        Route::post('/pelicula', [PeliculaController::class, 'store'])->name('peliculas.store');
        Route::put('pelicula/{id}', [PeliculaController::class, 'update'])->name('peliculas.update');

        // Ruta para los asientos
        Route::get('/asientos', [AsientoController::class, 'show'])->name('asientos.show');
        Route::post('/asientos/{id}/reservar', [AsientoController::class, 'reservar'])->name('asientos.reservar');
        Route::delete('reserva/{id}', [ReservaController::class, 'destroy'])->name('reserva.destroy');
        Route::get('/reservas/create', [ReservaController::class, 'create'])->name('reserva.create');
        Route::post('/reservas', [ReservaController::class, 'store'])->name('reserva.store');


    });

});

Route::get('/inicio', [ViewUserController::class, 'inicio'])->name('viewuser.inicio');
Route::get('/nosotros', [ViewUserController::class, 'nosotros'])->name('viewuser.nosotros');
Route::get('/proyecciones', [ViewUserController::class, 'proyeccion'])->name('viewuser.proyeccion');
Route::get('/sucursales', [ViewUserController::class, 'sucursales'])->name('viewuser.sucursales');

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
@component('components.layouts')
    @component('components.main')
    @endcomponent

    <h1>Nuestras Recomendaciones</h1>
    <br>
    <x-recientes />
    <br>
    <h2> Mas informacion </h2>


@endcomponent

resources/views/navigation-menu.blade.php
<nav x-data="{ open: false }" class="navbar navbar-expand-lg navbar-light bg-dark">
    <!-- Primary Navigation Menu -->
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ route('dashboard') }}">
            <x-application-mark class="block h-9 w-auto" />
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <x-nav-link href="{{ route('dashboard') }}" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </li>
            </ul>
            <hr>

            <ul class="navbar-nav">
                <!-- Teams Dropdown -->
                @if (Laravel\Jetstream\Jetstream::hasTeamFeatures())
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="teamsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            {{ Auth::user()->currentTeam->name }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="teamsDropdown">
                            <li><a class="dropdown-item" href="{{ route('teams.show', Auth::user()->currentTeam->id) }}">{{ __('Team Settings') }}</a></li>
                            @can('create', Laravel\Jetstream\Jetstream::newTeamModel())
                                <li><a class="dropdown-item" href="{{ route('teams.create') }}">{{ __('Create New Team') }}</a></li>
                            @endcan
                            <li><hr class="dropdown-divider"></li>
                            @foreach (Auth::user()->allTeams() as $team)
                                <li><a class="dropdown-item" href="{{ route('teams.switch', $team->id) }}">{{ $team->name }}</a></li>
                            @endforeach
                        </ul>
                    </li>
                @endif

                <!-- Settings Dropdown -->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        @if (Laravel\Jetstream\Jetstream::managesProfilePhotos())
                            <img class="rounded-circle" width="32" height="32" src="{{ Auth::user()->profile_photo_url }}" alt="{{ Auth::user()->name }}" />
                        @else
                            {{ Auth::user()->name }}
                        @endif
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><a class="dropdown-item" href="{{ route('profile.show') }}">{{ __('Profile') }}</a></li>
                        @if (Laravel\Jetstream\Jetstream::hasApiFeatures())
                            <li><a class="dropdown-item" href="{{ route('api-tokens.index') }}">{{ __('API Tokens') }}</a></li>
                        @endif
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <form method="POST" action="{{ route('logout') }}">
                                @csrf
                                <x-dropdown-link :href="route('logout')"
                                        onclick="event.preventDefault();
                                                    this.closest('form').submit();">
                                    {{ __('Log Out') }}
                                </x-dropdown-link>
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100 dark:bg-gray-900">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg prose dark:prose-invert">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100 dark:bg-gray-900">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white dark:bg-gray-800 shadow-md overflow-hidden sm:rounded-lg prose dark:prose-invert">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>